import Categories from "./components/Categories";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Roboto } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-black`}>
        <Navbar />
        <main className="flex justify-center items-center">
          <div className="container">
            <Categories />
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
